---
title: "Первый опыт использования языка R"
output: 
  learnr::tutorial:
    language: ru.json
runtime: shiny_prerendered

---
```{r setup-locale, include=FALSE}
Sys.setenv(LANGUAGE = "ru_RU.UTF-8")
Sys.setlocale("LC_ALL", "Russian")
```


```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(webexercises)
library(tutorial.helpers)
knitr::opts_chunk$set(echo = FALSE)
```

##

```{r info-section, child = "child_documents/info_section.Rmd"}
```

## Самостоятельная работа 0

**1. Ответьте на несколько вопросов:**

```{r q1}
question_radio(
  "Каким языком является R?",
  answer("компилируемым"),
  answer("интерпретируемым", correct = TRUE),
  answer("процедурным"),
  answer("структурным"),
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```

```{r q2}
question_radio(
  "Может ли R быть интегрирован с Hadoop для обработки больших данных?",
  answer("Нет"),
  answer("Да", correct = TRUE),
  allow_retry = TRUE,
  random_answer_order = F
)
```

```{r q3}
question_radio(
  "На основе какого языка создан R?",
  answer("Python"),
  answer("S", correct = TRUE),
  answer("Oracle"),
  answer("Java"),
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```


**2. Используя арифметические операторы, напишите код, находящий целую часть (без остатка) следующего выражения: $$\frac{5^2+10^3}3$$. **

В ответе должно получиться 341.

```{r ex2, exercise = TRUE}
# Напишите свой код здесь

```

```{r ex2-solution}
# with ^ ----
(5^2+10^3) %/% 3

# with ** ----
(5**2+10**3) %/% 3
```

```{r ex2-code-check}
grade_code()
```

3.  Напишите код, выводящий на экран текстовое сообщение "Я люблю Барнаул!"

```{r ex3, exercise = TRUE}
# Напишите свой код здесь

```

```{r ex3-solution}
print("Я люблю Барнаул!")
```

```{r ex3-code-check}
grade_code()
```

```{r download-answers, child ="child_documents/download_answers.Rmd"}
```

